---
- name: install and update postgresql dependencies
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - libpq-dev
    - python-dev
    - python-psycopg2
- name: install and update postgresql
  become: yes
  apt: pkg={{item}} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
  notify: restart postgresql
- name: ensure the postgreSQL service is running
  service: name=postgresql state=started enabled=yes
- name: create db
  postgresql_db: name="{{ db_name }}"
  become: yes
  become_user: postgres
- name: create postgresql user and grant access to db
  postgresql_user: db="{{ db_name }}" name="{{ db_user }}" password="{{ db_pass }}"
  become: yes
  become_user: postgres